name: Build Executables (Windows & macOS)

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]  # 只跑 Windows & Mac

    steps:
      # 1. 拉取源码
      - uses: actions/checkout@v4

      # 2. 安装 Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller upx  # 安装打包 + 压缩工具

      # 4. 打包（排除不必要模块，体积更小）
      - name: Build executable
        run: |
          pyinstaller --onefile --clean `
            --exclude-module tkinter `
            --exclude-module test `
            --exclude-module email `
            main.py
        shell: pwsh
        if: matrix.os == 'windows-latest'

      - name: Build executable (Mac)
        run: |
          pyinstaller --onefile --clean \
            --exclude-module tkinter \
            --exclude-module test \
            --exclude-module email \
            main.py
        shell: bash
        if: matrix.os == 'macos-latest'

      # 5. 压缩可执行文件
      - name: Compress (UPX)
        run: |
          upx dist/*
        shell: bash

      # 6. 上传打包文件
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-${{ matrix.os }}
          path: dist/*
