name: Build PPTgenerator (Windows & macOS)

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: x64
            suffix: ""
          - os: macos-13  # Intel Mac (免费runner)
            arch: x64
            suffix: "-intel"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # 安装 UPX (不同系统不同方法)
      - name: Install UPX on macOS
        if: startsWith(matrix.os, 'macos-')
        run: brew install upx

      - name: Install UPX on Windows
        if: matrix.os == 'windows-latest'
        run: choco install upx -y
        shell: pwsh

      # 打包（不同平台排除不必要模块，减小体积）
      - name: Build executable (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --onefile --console --optimize=2 --clean `
            --exclude-module tkinter `
            --exclude-module matplotlib `
            --exclude-module scipy `
            --exclude-module IPython `
            --exclude-module jupyter `
            --exclude-module notebook `
            --exclude-module pytest `
            --exclude-module setuptools `
            --exclude-module distutils `
            --exclude-module pip `
            --hidden-import=uvicorn.loops.auto `
            --hidden-import=uvicorn.protocols.http.auto `
            --hidden-import=uvicorn.protocols.websockets.auto `
            --hidden-import=uvicorn.lifespan.on `
            --add-data "static;static" `
            --add-data "prompts;prompts" `
            --add-data "tools/pptx_json.json;tools" `
            --add-data "模板.pptx;." `
            --name "PPTgenerator" `
            web_app.py
        shell: pwsh

      - name: Build executable (Mac)
        if: startsWith(matrix.os, 'macos-')
        run: |
          pyinstaller --onefile --console --optimize=2 --clean \
            --exclude-module tkinter \
            --exclude-module matplotlib \
            --exclude-module scipy \
            --exclude-module IPython \
            --exclude-module jupyter \
            --exclude-module notebook \
            --exclude-module pytest \
            --exclude-module setuptools \
            --exclude-module distutils \
            --exclude-module pip \
            --hidden-import=uvicorn.loops.auto \
            --hidden-import=uvicorn.protocols.http.auto \
            --hidden-import=uvicorn.protocols.websockets.auto \
            --hidden-import=uvicorn.lifespan.on \
            --add-data "static:static" \
            --add-data "prompts:prompts" \
            --add-data "tools/pptx_json.json:tools" \
            --add-data "模板.pptx:." \
            --name "PPTgenerator${{ matrix.suffix }}" \
            web_app.py
        shell: bash

      # 设置 macOS 可执行文件权限
      - name: Set executable permissions (macOS)
        if: startsWith(matrix.os, 'macos-')
        run: chmod +x dist/PPTgenerator${{ matrix.suffix }}
        shell: bash

      # 压缩（跳过失败的文件）
      - name: Compress with UPX
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            upx --best dist/*.exe || echo "UPX compression failed, continuing..."
          else
            upx --best dist/* || echo "UPX compression failed, continuing..."
          fi
        shell: bash

      # 再次设置权限（UPX压缩后可能丢失权限）
      - name: Restore executable permissions (macOS)
        if: startsWith(matrix.os, 'macos-')
        run: chmod +x dist/PPTgenerator${{ matrix.suffix }}
        shell: bash

      # macOS 代码签名 (ad-hoc签名，避免"未知开发者"警告)
      - name: Code sign executable (macOS)
        if: startsWith(matrix.os, 'macos-')
        run: |
          codesign --force --deep --sign - dist/PPTgenerator${{ matrix.suffix }}
          echo "macOS应用已签名"
        shell: bash

      # 上传 Artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PPTgenerator-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/*
